In [145]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import missingno as msno
import seaborn as sns
from sklearn.model_selection import train_test_split, KFold
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error, r2_score
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LinearRegression
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split, KFold
import numpy as np
from sklearn.base import clone
import importlib
import utils
importlib.reload(utils)
from utils import plot_y_yhat,clean_train_data,error_metric, predict_average,baseline_cross_validation
from sklearn.experimental import enable_iterative_imputer  
from sklearn.impute import SimpleImputer, KNNImputer, IterativeImputer
from sklearn.impute import MissingIndicator
from sklearn.experimental import enable_iterative_imputer  # noqa: F401

In [146]:
train=pd.read_csv('../data/train_data.csv')
test=pd.read_csv('../data/test_data.csv')
sample_submission=pd.read_csv('../data/sample_submission.csv')

In [147]:
train.head()

,id,Age,Gender,Stage,GeneticRisk,TreatmentType,ComorbidityIndex,TreatmentResponse,SurvivalTime,Censored
0,0,65.0,0,2,1.0,0,0.0,0.0,4.2,0
1,1,68.0,1,2,0.0,1,1.0,1.0,4.7,1
2,2,68.0,1,3,1.0,1,0.0,1.0,3.5,1
3,3,81.0,1,4,1.0,1,3.0,0.0,2.3,0
4,4,59.0,1,2,1.0,0,NaN,0.0,NaN,0

In [148]:
train.isna().sum()

id                     0
Age                    0
Gender                 0
Stage                  0
GeneticRisk           85
TreatmentType          0
ComorbidityIndex      45
TreatmentResponse     29
SurvivalTime         160
Censored               0
dtype: int64

In [149]:
# Keep only rows where SurvivalTime is not NaN
df = train.dropna(subset=["SurvivalTime"])

# Define the columns to impute
cols_to_impute = ["GeneticRisk", "ComorbidityIndex", "TreatmentResponse"]

print("Shape after removing rows with missing SurvivalTime:", df.shape)
print("Remaining NaNs per column:\n", df.isna().sum())

Shape after removing rows with missing SurvivalTime: (240, 10)
Remaining NaNs per column:
 id                    0
Age                   0
Gender                0
Stage                 0
GeneticRisk          47
TreatmentType         0
ComorbidityIndex     30
TreatmentResponse    16
SurvivalTime          0
Censored              0
dtype: int64

In [150]:
# --- Zero Imputation ---
imputer = SimpleImputer(strategy="constant", fill_value=0, add_indicator=True)
transformed = imputer.fit_transform(df[cols_to_impute])

# Indicator columns for missing values
indicator_cols = [f"{col}_missing" for col in cols_to_impute]

df_zero = df.copy()
df_zero[cols_to_impute + indicator_cols] = transformed

print("Zero Imputation - Remaining NaNs:\n", df_zero.isna().sum())
df_zero.head(10)

Zero Imputation - Remaining NaNs:
 id                           0
Age                          0
Gender                       0
Stage                        0
GeneticRisk                  0
TreatmentType                0
ComorbidityIndex             0
TreatmentResponse            0
SurvivalTime                 0
Censored                     0
GeneticRisk_missing          0
ComorbidityIndex_missing     0
TreatmentResponse_missing    0
dtype: int64

,id,Age,Gender,Stage,GeneticRisk,TreatmentType,ComorbidityIndex,TreatmentResponse,SurvivalTime,Censored,GeneticRisk_missing,ComorbidityIndex_missing,TreatmentResponse_missing
0,0,65.0,0,2,1.0,0,0.0,0.0,4.2,0,0.0,0.0,0.0
1,1,68.0,1,2,0.0,1,1.0,1.0,4.7,1,0.0,0.0,0.0
2,2,68.0,1,3,1.0,1,0.0,1.0,3.5,1,0.0,0.0,0.0
3,3,81.0,1,4,1.0,1,3.0,0.0,2.3,0,0.0,0.0,0.0
5,5,47.0,1,4,1.0,1,0.0,0.0,2.6,0,0.0,1.0,0.0
9,9,68.0,1,1,0.0,0,1.0,1.0,6.4,0,0.0,0.0,0.0
11,11,56.0,0,2,1.0,0,0.0,1.0,4.1,0,0.0,1.0,0.0
12,12,66.0,1,2,0.0,0,1.0,1.0,9.1,0,0.0,0.0,0.0
14,14,77.0,0,3,0.0,1,2.0,0.0,3.3,1,1.0,0.0,0.0
16,16,63.0,1,1,1.0,1,1.0,1.0,3.0,0,0.0,0.0,0.0

In [151]:
# --- Mean Imputation ---
imputer = SimpleImputer(strategy="mean", add_indicator=True)
transformed = imputer.fit_transform(df[cols_to_impute])

df_mean = df.copy()
df_mean[cols_to_impute + indicator_cols] = transformed

print("Mean Imputation - Remaining NaNs:\n", df_mean.isna().sum())
df_mean.head(10)

Mean Imputation - Remaining NaNs:
 id                           0
Age                          0
Gender                       0
Stage                        0
GeneticRisk                  0
TreatmentType                0
ComorbidityIndex             0
TreatmentResponse            0
SurvivalTime                 0
Censored                     0
GeneticRisk_missing          0
ComorbidityIndex_missing     0
TreatmentResponse_missing    0
dtype: int64

,id,Age,Gender,Stage,GeneticRisk,TreatmentType,ComorbidityIndex,TreatmentResponse,SurvivalTime,Censored,GeneticRisk_missing,ComorbidityIndex_missing,TreatmentResponse_missing
0,0,65.0,0,2,1.000000,0,0.000000,0.0,4.2,0,0.0,0.0,0.0
1,1,68.0,1,2,0.000000,1,1.000000,1.0,4.7,1,0.0,0.0,0.0
2,2,68.0,1,3,1.000000,1,0.000000,1.0,3.5,1,0.0,0.0,0.0
3,3,81.0,1,4,1.000000,1,3.000000,0.0,2.3,0,0.0,0.0,0.0
5,5,47.0,1,4,1.000000,1,1.047619,0.0,2.6,0,0.0,1.0,0.0
9,9,68.0,1,1,0.000000,0,1.000000,1.0,6.4,0,0.0,0.0,0.0
11,11,56.0,0,2,1.000000,0,1.047619,1.0,4.1,0,0.0,1.0,0.0
12,12,66.0,1,2,0.000000,0,1.000000,1.0,9.1,0,0.0,0.0,0.0
14,14,77.0,0,3,0.284974,1,2.000000,0.0,3.3,1,1.0,0.0,0.0
16,16,63.0,1,1,1.000000,1,1.000000,1.0,3.0,0,0.0,0.0,0.0

In [152]:
# --- Median Imputation ---
imputer = SimpleImputer(strategy="median", add_indicator=True)
transformed = imputer.fit_transform(df[cols_to_impute])

df_median = df.copy()
df_median[cols_to_impute + indicator_cols] = transformed

print("Median Imputation - Remaining NaNs:\n", df_median.isna().sum())
df_median.head(10)

Median Imputation - Remaining NaNs:
 id                           0
Age                          0
Gender                       0
Stage                        0
GeneticRisk                  0
TreatmentType                0
ComorbidityIndex             0
TreatmentResponse            0
SurvivalTime                 0
Censored                     0
GeneticRisk_missing          0
ComorbidityIndex_missing     0
TreatmentResponse_missing    0
dtype: int64

,id,Age,Gender,Stage,GeneticRisk,TreatmentType,ComorbidityIndex,TreatmentResponse,SurvivalTime,Censored,GeneticRisk_missing,ComorbidityIndex_missing,TreatmentResponse_missing
0,0,65.0,0,2,1.0,0,0.0,0.0,4.2,0,0.0,0.0,0.0
1,1,68.0,1,2,0.0,1,1.0,1.0,4.7,1,0.0,0.0,0.0
2,2,68.0,1,3,1.0,1,0.0,1.0,3.5,1,0.0,0.0,0.0
3,3,81.0,1,4,1.0,1,3.0,0.0,2.3,0,0.0,0.0,0.0
5,5,47.0,1,4,1.0,1,1.0,0.0,2.6,0,0.0,1.0,0.0
9,9,68.0,1,1,0.0,0,1.0,1.0,6.4,0,0.0,0.0,0.0
11,11,56.0,0,2,1.0,0,1.0,1.0,4.1,0,0.0,1.0,0.0
12,12,66.0,1,2,0.0,0,1.0,1.0,9.1,0,0.0,0.0,0.0
14,14,77.0,0,3,0.0,1,2.0,0.0,3.3,1,1.0,0.0,0.0
16,16,63.0,1,1,1.0,1,1.0,1.0,3.0,0,0.0,0.0,0.0

In [153]:
# --- KNN Imputation + Missing Indicators ---
imputer = KNNImputer(n_neighbors=5, weights="uniform")
indicator = MissingIndicator()  # crée les colonnes indicatrices

# Fit imputers
imputer.fit(df[cols_to_impute])
missing_mask = indicator.fit_transform(df[cols_to_impute]).astype(int)  # Convert True/False -> 1/0

# Transform data
transformed = imputer.transform(df[cols_to_impute])

# Build final DataFrame
df_knn_indicator = df.copy()
df_knn_indicator[cols_to_impute] = transformed

# Add indicator columns manually with consistent naming
indicator_cols = [f"{df[cols_to_impute].columns[i]}_missing" for i in indicator.features_]
df_knn_indicator[indicator_cols] = missing_mask

print("KNN Imputation + Indicators - Remaining NaNs:\n", df_knn_indicator.isna().sum())
df_knn_indicator.head(10)

KNN Imputation + Indicators - Remaining NaNs:
 id                           0
Age                          0
Gender                       0
Stage                        0
GeneticRisk                  0
TreatmentType                0
ComorbidityIndex             0
TreatmentResponse            0
SurvivalTime                 0
Censored                     0
GeneticRisk_missing          0
ComorbidityIndex_missing     0
TreatmentResponse_missing    0
dtype: int64

,id,Age,Gender,Stage,GeneticRisk,TreatmentType,ComorbidityIndex,TreatmentResponse,SurvivalTime,Censored,GeneticRisk_missing,ComorbidityIndex_missing,TreatmentResponse_missing
0,0,65.0,0,2,1.0,0,0.0,0.0,4.2,0,0,0,0
1,1,68.0,1,2,0.0,1,1.0,1.0,4.7,1,0,0,0
2,2,68.0,1,3,1.0,1,0.0,1.0,3.5,1,0,0,0
3,3,81.0,1,4,1.0,1,3.0,0.0,2.3,0,0,0,0
5,5,47.0,1,4,1.0,1,1.2,0.0,2.6,0,0,1,0
9,9,68.0,1,1,0.0,0,1.0,1.0,6.4,0,0,0,0
11,11,56.0,0,2,1.0,0,0.4,1.0,4.1,0,0,1,0
12,12,66.0,1,2,0.0,0,1.0,1.0,9.1,0,0,0,0
14,14,77.0,0,3,0.6,1,2.0,0.0,3.3,1,1,0,0
16,16,63.0,1,1,1.0,1,1.0,1.0,3.0,0,0,0,0

In [154]:
# --- Iterative Imputation + Missing Indicators ---
imputer = IterativeImputer(max_iter=10, random_state=42)
indicator = MissingIndicator()  # crée les colonnes indicatrices

# Fit imputers
imputer.fit(df[cols_to_impute])
missing_mask = indicator.fit_transform(df[cols_to_impute]).astype(int)  # Convert True/False -> 1/0

# Transform data
transformed = imputer.transform(df[cols_to_impute])

# Build final DataFrame
df_iter_indicator1 = df.copy()
df_iter_indicator1[cols_to_impute] = transformed

# Add indicator columns manuellement avec nommage <colonne>_missing
indicator_cols = [f"{df[cols_to_impute].columns[i]}_missing" for i in indicator.features_]
df_iter_indicator1[indicator_cols] = missing_mask

print("Iterative Imputation + Indicators - Remaining NaNs:\n", df_iter_indicator1.isna().sum())
df_iter_indicator1.head(10)

Iterative Imputation + Indicators - Remaining NaNs:
 id                           0
Age                          0
Gender                       0
Stage                        0
GeneticRisk                  0
TreatmentType                0
ComorbidityIndex             0
TreatmentResponse            0
SurvivalTime                 0
Censored                     0
GeneticRisk_missing          0
ComorbidityIndex_missing     0
TreatmentResponse_missing    0
dtype: int64

,id,Age,Gender,Stage,GeneticRisk,TreatmentType,ComorbidityIndex,TreatmentResponse,SurvivalTime,Censored,GeneticRisk_missing,ComorbidityIndex_missing,TreatmentResponse_missing
0,0,65.0,0,2,1.000000,0,0.000000,0.0,4.2,0,0,0,0
1,1,68.0,1,2,0.000000,1,1.000000,1.0,4.7,1,0,0,0
2,2,68.0,1,3,1.000000,1,0.000000,1.0,3.5,1,0,0,0
3,3,81.0,1,4,1.000000,1,3.000000,0.0,2.3,0,0,0,0
5,5,47.0,1,4,1.000000,1,1.047547,0.0,2.6,0,0,1,0
9,9,68.0,1,1,0.000000,0,1.000000,1.0,6.4,0,0,0,0
11,11,56.0,0,2,1.000000,0,1.047244,1.0,4.1,0,0,1,0
12,12,66.0,1,2,0.000000,0,1.000000,1.0,9.1,0,0,0,0
14,14,77.0,0,3,0.284862,1,2.000000,0.0,3.3,1,1,0,0
16,16,63.0,1,1,1.000000,1,1.000000,1.0,3.0,0,0,0,0

In [155]:
# --- Most Frequent Imputation ---
# Goal: Replace missing values using the most frequent value of each column

imputer = SimpleImputer(strategy="most_frequent", add_indicator=True)
transformed = imputer.fit_transform(df[cols_to_impute])

# Create new indicator columns (same naming as your previous blocks)
indicator_cols = [f"{col}_missing" for col in cols_to_impute]

df_mostfreq = df.copy()
df_mostfreq[cols_to_impute + indicator_cols] = transformed

print("Most Frequent Imputation - Remaining NaNs:\n", df_mostfreq.isna().sum())
df_mostfreq.head(10)

Most Frequent Imputation - Remaining NaNs:
 id                           0
Age                          0
Gender                       0
Stage                        0
GeneticRisk                  0
TreatmentType                0
ComorbidityIndex             0
TreatmentResponse            0
SurvivalTime                 0
Censored                     0
GeneticRisk_missing          0
ComorbidityIndex_missing     0
TreatmentResponse_missing    0
dtype: int64

,id,Age,Gender,Stage,GeneticRisk,TreatmentType,ComorbidityIndex,TreatmentResponse,SurvivalTime,Censored,GeneticRisk_missing,ComorbidityIndex_missing,TreatmentResponse_missing
0,0,65.0,0,2,1.0,0,0.0,0.0,4.2,0,0.0,0.0,0.0
1,1,68.0,1,2,0.0,1,1.0,1.0,4.7,1,0.0,0.0,0.0
2,2,68.0,1,3,1.0,1,0.0,1.0,3.5,1,0.0,0.0,0.0
3,3,81.0,1,4,1.0,1,3.0,0.0,2.3,0,0.0,0.0,0.0
5,5,47.0,1,4,1.0,1,1.0,0.0,2.6,0,0.0,1.0,0.0
9,9,68.0,1,1,0.0,0,1.0,1.0,6.4,0,0.0,0.0,0.0
11,11,56.0,0,2,1.0,0,1.0,1.0,4.1,0,0.0,1.0,0.0
12,12,66.0,1,2,0.0,0,1.0,1.0,9.1,0,0.0,0.0,0.0
14,14,77.0,0,3,0.0,1,2.0,0.0,3.3,1,1.0,0.0,0.0
16,16,63.0,1,1,1.0,1,1.0,1.0,3.0,0,0.0,0.0,0.0

In [156]:
# --- Iterative Imputation with Missing Indicators ---
imputer = IterativeImputer(max_iter=10, random_state=42, sample_posterior=False)
indicator = MissingIndicator()  # crée les colonnes indicatrices

# Fit imputers
imputer.fit(df[cols_to_impute])
missing_mask = indicator.fit_transform(df[cols_to_impute]).astype(int)  # Convert True/False -> 1/0

# Perform imputation
transformed = imputer.transform(df[cols_to_impute])

# Build final DataFrame
df_iter_indicator2 = df.copy()
df_iter_indicator2[cols_to_impute] = transformed

# Add indicator columns manuellement avec nommage <colonne>_missing
indicator_cols = [df[cols_to_impute].columns[i] + "_missing" for i in indicator.features_]
df_iter_indicator2[indicator_cols] = missing_mask

print("Iterative Imputation + Indicators - Remaining NaNs:\n", df_iter_indicator2.isna().sum())
df_iter_indicator2.head(10)

Iterative Imputation + Indicators - Remaining NaNs:
 id                           0
Age                          0
Gender                       0
Stage                        0
GeneticRisk                  0
TreatmentType                0
ComorbidityIndex             0
TreatmentResponse            0
SurvivalTime                 0
Censored                     0
GeneticRisk_missing          0
ComorbidityIndex_missing     0
TreatmentResponse_missing    0
dtype: int64

,id,Age,Gender,Stage,GeneticRisk,TreatmentType,ComorbidityIndex,TreatmentResponse,SurvivalTime,Censored,GeneticRisk_missing,ComorbidityIndex_missing,TreatmentResponse_missing
0,0,65.0,0,2,1.000000,0,0.000000,0.0,4.2,0,0,0,0
1,1,68.0,1,2,0.000000,1,1.000000,1.0,4.7,1,0,0,0
2,2,68.0,1,3,1.000000,1,0.000000,1.0,3.5,1,0,0,0
3,3,81.0,1,4,1.000000,1,3.000000,0.0,2.3,0,0,0,0
5,5,47.0,1,4,1.000000,1,1.047547,0.0,2.6,0,0,1,0
9,9,68.0,1,1,0.000000,0,1.000000,1.0,6.4,0,0,0,0
11,11,56.0,0,2,1.000000,0,1.047244,1.0,4.1,0,0,1,0
12,12,66.0,1,2,0.000000,0,1.000000,1.0,9.1,0,0,0,0
14,14,77.0,0,3,0.284862,1,2.000000,0.0,3.3,1,1,0,0
16,16,63.0,1,1,1.000000,1,1.000000,1.0,3.0,0,0,0,0

In [157]:
# Create indicator for missing values
indicator = MissingIndicator()
missing_mask = indicator.fit_transform(df[cols_to_impute])

# Build column names using cols_to_impute indices
indicator_cols = [f"{cols_to_impute[i]}_missing" for i in indicator.features_]

# Convert boolean mask to integer (0/1)
missing_mask_int = missing_mask.astype(int)

# Build final DataFrame
df_indicator_only = df.copy()
df_indicator_only[indicator_cols] = missing_mask_int

print("Missing Indicator Only - No Imputation Applied")
df_indicator_only.head(10)

Missing Indicator Only - No Imputation Applied

,id,Age,Gender,Stage,GeneticRisk,TreatmentType,ComorbidityIndex,TreatmentResponse,SurvivalTime,Censored,GeneticRisk_missing,ComorbidityIndex_missing,TreatmentResponse_missing
0,0,65.0,0,2,1.0,0,0.0,0.0,4.2,0,0,0,0
1,1,68.0,1,2,0.0,1,1.0,1.0,4.7,1,0,0,0
2,2,68.0,1,3,1.0,1,0.0,1.0,3.5,1,0,0,0
3,3,81.0,1,4,1.0,1,3.0,0.0,2.3,0,0,0,0
5,5,47.0,1,4,1.0,1,NaN,0.0,2.6,0,0,1,0
9,9,68.0,1,1,0.0,0,1.0,1.0,6.4,0,0,0,0
11,11,56.0,0,2,1.0,0,NaN,1.0,4.1,0,0,1,0
12,12,66.0,1,2,0.0,0,1.0,1.0,9.1,0,0,0,0
14,14,77.0,0,3,NaN,1,2.0,0.0,3.3,1,1,0,0
16,16,63.0,1,1,1.0,1,1.0,1.0,3.0,0,0,0,0

In [158]:
def manage_indicator_columns(df, keep_indicator=True):
    """
    Return a DataFrame with or without the indicator columns.
    
    Parameters:
    -----------
    df : pd.DataFrame
        The dataset containing the original and indicator columns.
    keep_indicator : bool
        If True, keep columns containing '_missing'.
        If False, drop these columns.
    
    Returns:
    --------
    pd.DataFrame
        The modified DataFrame according to keep_indicator.
    """
    if keep_indicator:
        return df.copy()
    else:
        # Drop all columns with '_missing' in their name
        cols_to_drop = [col for col in df.columns if "_missing" in col]
        return df.drop(columns=cols_to_drop)

In [159]:
# --- Zero Imputation ---
df_zero_with = manage_indicator_columns(df_zero, keep_indicator=True)
df_zero_without = manage_indicator_columns(df_zero, keep_indicator=False)

# --- Mean Imputation ---
df_mean_with = manage_indicator_columns(df_mean, keep_indicator=True)
df_mean_without = manage_indicator_columns(df_mean, keep_indicator=False)

# --- Median Imputation ---
df_median_with = manage_indicator_columns(df_median, keep_indicator=True)
df_median_without = manage_indicator_columns(df_median, keep_indicator=False)

# --- KNN Imputation  ---
df_knn_with = manage_indicator_columns(df_knn_indicator, keep_indicator=True)
df_knn_without = manage_indicator_columns(df_knn_indicator, keep_indicator=False)

# --- Iterative Imputation + Missing Indicators (version 1) ---
df_iter1_with = manage_indicator_columns(df_iter_indicator1, keep_indicator=True)
df_iter1_without = manage_indicator_columns(df_iter_indicator1, keep_indicator=False)

# --- Most Frequent Imputation ---
df_mostfreq_with = manage_indicator_columns(df_mostfreq, keep_indicator=True)
df_mostfreq_without = manage_indicator_columns(df_mostfreq, keep_indicator=False)

# --- Iterative Imputation with Missing Indicators (version 2) ---
df_iter2_with = manage_indicator_columns(df_iter_indicator2, keep_indicator=True)
df_iter2_without = manage_indicator_columns(df_iter_indicator2, keep_indicator=False)

# --- Missing Indicator Only ---
df_indicator_only_with = manage_indicator_columns(df_indicator_only, keep_indicator=True)
df_indicator_only_without = manage_indicator_columns(df_indicator_only, keep_indicator=False)